### ISSUE TITLE
[Question] Selection Y counting

### ISSUE THREAD

**Issue by slava110** [itsmeow/ClaimIt#1]
If ClaimIt will claim everything from y=0 to y=255 then why it's counting selection Y?
There's no difference if I'll claim area 3x3x3 or 3x3x1 (for protection). But if I'll do the first way then 9 blocks will be removed from available blocks to claim.

**Comment by itsmeow** [comment]
What? ClaimIt has no sense of the Y dimension at all. Y dimension is not counted in claim block limits either.

**Comment by slava110** [comment]
Nah, sorry, my mistake :I
(Sorry for stupid issue)
