### ISSUE TITLE
Exception while ticking block

### ISSUE THREAD

**Issue by AhiVT** [itsmeow/ClaimIt#2]
**Describe the bug**
ClaimIt becomes stuck in an infinite loop (`java.lang.StackOverflowError`) with SpongeForge's PhaseTracker.
[crash-2019-10-21_20.29.34-server.txt](https://github.com/itsmeow/ClaimIt/files/3753537/crash-2019-10-21_20.29.34-server.txt)

**To Reproduce**
No reliable reproduction yet.

**Expected behavior**
Server is able to tick the block.

**Versions**
 - Forge Version: 14.23.5.2846
 - SpongeForge Version (if applicable): 1.12.2-2838-7.1.7-RC3928
 - Mod Version: 1.12.2-1.1.1
 - API Version: 1.12.2-1.1.1

**Comment by itsmeow** [comment]
Huh. Looks like I need to check the previous state to ensure it isn't fire so that the fire doesn't trigger itself repeatedly or something. I'm surprised this didn't appear during testing ever.
